
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-test-cluster
  region: eu-central-1
  version: "1.29"

# IAM OIDC (enables IRSA)
iam:
  withOIDC: true

managedNodeGroups:
  - name: test-nodes
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    volumeSize: 20
    volumeType: gp3
    labels:
      role: worker
      environment: test
    tags:
      purpose: cluster-validation
      managed-by: eksctl
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: false
        cloudWatch: true

# CloudWatch
cloudWatch:
  clusterLogging:
    enableTypes:
      - "api"
      - "audit"
      - "authenticator"
